# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    create_connection_configs_from_ids as create_connection_configs_from_ids,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    fetch_events as fetch_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    fetch_patrol_events as fetch_patrol_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    fetch_transects as fetch_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    get_server_name as get_server_name,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    get_survey_period_label as get_survey_period_label,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    split_connection_configs as split_connection_configs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    split_survey_by_period as split_survey_by_period,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    unpack_period_connection_survey as unpack_period_connection_survey,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    unpack_period_patrol_events as unpack_period_patrol_events,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    join_list_column as join_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    parse_df_point as parse_df_point,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    set_dataframe_index as set_dataframe_index,
)
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    format_text_column as format_text_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    add_constant_column as add_constant_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    build_hls_ndvi_image as build_hls_ndvi_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    build_palsar_woody_cover_image as build_palsar_woody_cover_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    build_slope_image as build_slope_image,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    get_server_subdomain as get_server_subdomain,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    get_survey_min_date as get_survey_min_date,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    label_features_with_image_stat as label_features_with_image_stat,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.io import (
    to_ee_feature_collection as to_ee_feature_collection,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    add_off_transect_distance as add_off_transect_distance,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    add_orig_geometry as add_orig_geometry,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    bfill_within_patrols as bfill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    buffer_transects as buffer_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    collect_patrol_events_paths as collect_patrol_events_paths,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    collect_transects_paths as collect_transects_paths,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    compute_field_effort as compute_field_effort,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    convert_column_timezone as convert_column_timezone,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    drop_null_columns as drop_null_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    estimate_animal_positions as estimate_animal_positions,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    estimate_utm_crs as estimate_utm_crs,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    extract_notes_text as extract_notes_text,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    ffill_within_patrols as ffill_within_patrols,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    filter_transect_lines_by_visited as filter_transect_lines_by_visited,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    filter_visited_transects as filter_visited_transects,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    flag_events_intersecting_transect as flag_events_intersecting_transect,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    format_publish_paths as format_publish_paths,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    join_with_underscore as join_with_underscore,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    merge_transect_lines as merge_transect_lines,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    normalize_name_spaces as normalize_name_spaces,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    parse_list_column as parse_list_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    simplify_transects as simplify_transects,
)
from ecoscope_workflows_ext_ste.tasks.filter import filter_rows as filter_rows


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    gee_client = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_client") or {}))
        .call()
    )

    connection_config = (
        task(create_connection_configs_from_ids)
        .validate()
        .set_task_instance_id("connection_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("connection_config") or {}))
        .call()
    )

    split_connection_config = (
        task(split_connection_configs)
        .validate()
        .set_task_instance_id("split_connection_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection_configs=connection_config,
            **(params.get("split_connection_config") or {}),
        )
        .call()
    )

    retrieve_patrol_events = (
        task(fetch_patrol_events)
        .validate()
        .set_task_instance_id("retrieve_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("retrieve_patrol_events") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=split_connection_config)
    )

    set_patrol_index = (
        task(set_dataframe_index)
        .validate()
        .set_task_instance_id("set_patrol_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="id", **(params.get("set_patrol_index") or {}))
        .mapvalues(argnames=["df"], argvalues=retrieve_patrol_events)
    )

    zip_conn_patrol_events = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_conn_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[split_connection_config, set_patrol_index],
            **(params.get("zip_conn_patrol_events") or {}),
        )
        .call()
    )

    period_split = (
        task(split_survey_by_period)
        .validate()
        .set_task_instance_id("period_split")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection_survey_and_events=zip_conn_patrol_events,
            **(params.get("period_split") or {}),
        )
        .call()
    )

    period_connection_survey = (
        task(unpack_period_connection_survey)
        .validate()
        .set_task_instance_id("period_connection_survey")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("period_connection_survey") or {}))
        .mapvalues(argnames=["pair"], argvalues=period_split)
    )

    period_patrol_events = (
        task(unpack_period_patrol_events)
        .validate()
        .set_task_instance_id("period_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("period_patrol_events") or {}))
        .mapvalues(argnames=["pair"], argvalues=period_split)
    )

    period_label = (
        task(get_survey_period_label)
        .validate()
        .set_task_instance_id("period_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection_survey_and_events=zip_conn_patrol_events,
            **(params.get("period_label") or {}),
        )
        .call()
    )

    fetch_patrol_transects = (
        task(fetch_transects)
        .validate()
        .set_task_instance_id("fetch_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("fetch_patrol_transects") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=period_connection_survey)
    )

    fetch_earthranger_client = (
        task(get_server_name)
        .validate()
        .set_task_instance_id("fetch_earthranger_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("fetch_earthranger_client") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=period_connection_survey)
    )

    fetch_er_domain_name = (
        task(get_server_name)
        .validate()
        .set_task_instance_id("fetch_er_domain_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("fetch_er_domain_name") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=period_connection_survey)
    )

    fetch_events_from_ids = (
        task(fetch_events)
        .validate()
        .set_task_instance_id("fetch_events_from_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(chunk_size=75, **(params.get("fetch_events_from_ids") or {}))
        .mapvalues(
            argnames=["connection_survey", "patrol_events"], argvalues=period_split
        )
    )

    filter_survey_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_survey_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_type",
            values=["distancecountpatrol_rep", "distance_count_patrol_metadata"],
            **(params.get("filter_survey_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
    )

    extract_lat_long = (
        task(parse_df_point)
        .validate()
        .set_task_instance_id("extract_lat_long")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("extract_lat_long") or {}))
        .mapvalues(argnames=["df"], argvalues=filter_survey_events)
    )

    normalize_reported_by = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="reported_by",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_reported_by") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=extract_lat_long)
    )

    extract_reported_by = (
        task(join_list_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="reported_by__name",
            separator=",",
            **(params.get("extract_reported_by") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_reported_by)
    )

    zip_conn_survey_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_conn_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[extract_reported_by, fetch_earthranger_client],
            **(params.get("zip_conn_survey_df") or {}),
        )
        .call()
    )

    process_survey_event_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_survey_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            map_to_titles=True,
            ordered=True,
            **(params.get("process_survey_event_details") or {}),
        )
        .mapvalues(argnames=["df", "client"], argvalues=zip_conn_survey_df)
    )

    normalize_survey_df = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_survey_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=process_survey_event_details)
    )

    map_survey_event_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_survey_event_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=False,
            drop_columns=["id"],
            retain_columns=[
                "serial_number",
                "event_type",
                "time",
                "Latitude",
                "Longitude",
                "reported_by__name",
                "event_details__Transect ID",
                "event_details__Transect_ID",
                "event_details__Team_members",
                "event_details__Team Members",
                "event_details__Number_of_observers",
                "event_details__Number of Observers",
            ],
            rename_columns={
                "time": "time",
                "event_type": "event_type",
                "title": "title",
                "geometry": "geometry",
                "serial_number": "serial_number",
                "patrol_id": "patrol_id",
                "patrol_serial_number": "patrol_serial_number",
                "reported_by__name": "reported_by",
                "Latitude": "latitude",
                "Longitude": "longitude",
                "event_details__Number_of_observers": "Number of Observers",
                "event_details__Team_members": "Team Members",
                "event_details__Transect_ID": "Transect ID",
                "event_details__Number of Observers": "Number of Observers",
                "event_details__Team Members": "Team Members",
                "event_details__Transect ID": "Transect ID",
            },
            **(params.get("map_survey_event_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_survey_df)
    )

    parse_team_members = (
        task(parse_list_column)
        .validate()
        .set_task_instance_id("parse_team_members")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="Team Members", **(params.get("parse_team_members") or {}))
        .mapvalues(argnames=["df"], argvalues=map_survey_event_columns)
    )

    join_team_members = (
        task(join_list_column)
        .validate()
        .set_task_instance_id("join_team_members")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="Team Members",
            separator=",",
            **(params.get("join_team_members") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=parse_team_members)
    )

    drop_null_cols = (
        task(drop_null_columns)
        .validate()
        .set_task_instance_id("drop_null_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("drop_null_cols") or {}))
        .mapvalues(argnames=["df"], argvalues=join_team_members)
    )

    retrieve_survey_name = (
        task(get_server_subdomain)
        .validate()
        .set_task_instance_id("retrieve_survey_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("retrieve_survey_name") or {}))
        .mapvalues(argnames=["connection_survey"], argvalues=period_connection_survey)
    )

    zip_name_period = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_name_period")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[retrieve_survey_name, period_label],
            **(params.get("zip_name_period") or {}),
        )
        .call()
    )

    combine_survey_period_name = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_survey_period_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("combine_survey_period_name") or {}))
        .mapvalues(argnames=["first", "second"], argvalues=zip_name_period)
    )

    combine_survey_event_names = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_survey_event_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            second="analysis_metadata",
            **(params.get("combine_survey_event_names") or {}),
        )
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_survey_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_survey_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_survey_event_names, drop_null_cols],
            **(params.get("zip_filename_survey_df") or {}),
        )
        .call()
    )

    persist_survey_event_metadata = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_survey_event_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            **(params.get("persist_survey_event_metadata") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=zip_filename_survey_df)
    )

    zip_connection_metadata = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_connection_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[period_connection_survey, drop_null_cols],
            **(params.get("zip_connection_metadata") or {}),
        )
        .call()
    )

    field_effort = (
        task(compute_field_effort)
        .validate()
        .set_task_instance_id("field_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("field_effort") or {}))
        .mapvalues(
            argnames=["connection_survey", "df"], argvalues=zip_connection_metadata
        )
    )

    combine_survey_field = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_survey_field")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(second="field_effort", **(params.get("combine_survey_field") or {}))
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_fe = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_fe")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_survey_field, field_effort],
            **(params.get("zip_filename_fe") or {}),
        )
        .call()
    )

    persist_field_effort = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_field_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            **(params.get("persist_field_effort") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=zip_filename_fe)
    )

    select_event_details = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["event_details", "notes"],
            raise_on_missing=False,
            **(params.get("select_event_details") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fetch_events_from_ids)
    )

    zip_patrol_events_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_patrol_events_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[period_patrol_events, select_event_details],
            **(params.get("zip_patrol_events_df") or {}),
        )
        .call()
    )

    merge_patrol_events = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            how="left",
            left_on=None,
            right_on=None,
            left_index=True,
            right_index=True,
            fillna_value=None,
            on=None,
            **(params.get("merge_patrol_events") or {}),
        )
        .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_events_df)
    )

    convert_tz_utc = (
        task(convert_column_timezone)
        .validate()
        .set_task_instance_id("convert_tz_utc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="time", time_range=time_range, **(params.get("convert_tz_utc") or {})
        )
        .mapvalues(argnames=["df"], argvalues=merge_patrol_events)
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_event_details") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=convert_tz_utc)
    )

    map_patrol_df = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=None,
            raise_if_not_found=False,
            retain_columns=None,
            rename_columns={
                "event_details__distancecountpatrol_numberofobservers": "num_observers",
                "event_details__distancecountpatrol_teammembers": "Team Members",
                "event_details__distancecountpatrol_transectid": "transect_id",
                "event_details__distancecountwildlife_distancetocentre": "dist_to_centre",
                "event_details__distancecountwildlife_numberofjuveniles": "num_juveniles",
                "event_details__distancecountwildlife_radialangle": "radialangle",
                "event_details__distancecountwildlife_species": "species",
                "event_details__distancecountwildlife_totalcount": "totalcount",
                "event_details__Transect_ID": "transect_id_v2",
                "event_details__Team_members": "Team Members",
                "event_details__Number_of_observers": "num_observers",
                "event_details__Number_of_Observers": "num_observers",
                "event_details__Number of Observers": "num_observers",
                "event_details__Species": "species",
                "event_details__Total Count": "totalcount",
                "event_details__Number of Juveniles": "num_juveniles",
                "event_details__Radial Angle": "radialangle",
                "event_details__Distance to Centre (m)": "dist_to_centre",
            },
            **(params.get("map_patrol_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=normalize_event_details)
    )

    normalize_transect_id = (
        task(map_columns)
        .validate()
        .set_task_instance_id("normalize_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=False,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"transect_id_v2": "transect_id"},
            **(params.get("normalize_transect_id") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=map_patrol_df)
    )

    parse_transect_id = (
        task(parse_list_column)
        .validate()
        .set_task_instance_id("parse_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="transect_id", **(params.get("parse_transect_id") or {}))
        .mapvalues(argnames=["df"], argvalues=normalize_transect_id)
    )

    join_transect_id = (
        task(join_list_column)
        .validate()
        .set_task_instance_id("join_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="transect_id",
            separator=",",
            **(params.get("join_transect_id") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=parse_transect_id)
    )

    lowercase_transect_id = (
        task(format_text_column)
        .validate()
        .set_task_instance_id("lowercase_transect_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="transect_id",
            method="lower",
            **(params.get("lowercase_transect_id") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=join_transect_id)
    )

    bfill_patrol_events = (
        task(bfill_within_patrols)
        .validate()
        .set_task_instance_id("bfill_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col="patrol_serial_number",
            columns=["transect_id", "num_observers"],
            skip_if_missing=True,
            **(params.get("bfill_patrol_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=lowercase_transect_id)
    )

    ffill_patrol_events = (
        task(ffill_within_patrols)
        .validate()
        .set_task_instance_id("ffill_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col="patrol_serial_number",
            columns=["transect_id", "num_observers"],
            skip_if_missing=True,
            **(params.get("ffill_patrol_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=bfill_patrol_events)
    )

    filter_wildlife_rep = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_wildlife_rep")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_type",
            values=["distancecountwildlife_rep"],
            **(params.get("filter_wildlife_rep") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ffill_patrol_events)
    )

    extract_notes = (
        task(extract_notes_text)
        .validate()
        .set_task_instance_id("extract_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="notes",
            new_column="other_species",
            **(params.get("extract_notes") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_wildlife_rep)
    )

    zip_conn_surv_name_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_conn_surv_name_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[extract_notes, combine_survey_period_name],
            **(params.get("zip_conn_surv_name_df") or {}),
        )
        .call()
    )

    add_survey_column = (
        task(add_constant_column)
        .validate()
        .set_task_instance_id("add_survey_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="survey_id", **(params.get("add_survey_column") or {}))
        .mapvalues(argnames=["df", "value"], argvalues=zip_conn_surv_name_df)
    )

    convert_transects_utm = (
        task(estimate_utm_crs)
        .validate()
        .set_task_instance_id("convert_transects_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("convert_transects_utm") or {}))
        .mapvalues(argnames=["geodataframe"], argvalues=fetch_patrol_transects)
    )

    zip_transect_df_crs = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_transect_df_crs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[convert_transects_utm, fetch_patrol_transects],
            **(params.get("zip_transect_df_crs") or {}),
        )
        .call()
    )

    reproject_transects_utm = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_transects_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("reproject_transects_utm") or {}))
        .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_transect_df_crs)
    )

    normalize_transect_names_utm = (
        task(format_text_column)
        .validate()
        .set_task_instance_id("normalize_transect_names_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="name",
            method="lower",
            **(params.get("normalize_transect_names_utm") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=reproject_transects_utm)
    )

    normalize_transect_underscores = (
        task(normalize_name_spaces)
        .validate()
        .set_task_instance_id("normalize_transect_underscores")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="name", **(params.get("normalize_transect_underscores") or {}))
        .mapvalues(argnames=["df"], argvalues=normalize_transect_names_utm)
    )

    zip_patrol_df_crs = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_patrol_df_crs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[convert_transects_utm, add_survey_column],
            **(params.get("zip_patrol_df_crs") or {}),
        )
        .call()
    )

    patrol_events_utm = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("patrol_events_utm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_events_utm") or {}))
        .mapvalues(argnames=["target_crs", "gdf"], argvalues=zip_patrol_df_crs)
    )

    zip_patrol_transects = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[patrol_events_utm, normalize_transect_underscores],
            **(params.get("zip_patrol_transects") or {}),
        )
        .call()
    )

    observers_distance = (
        task(add_off_transect_distance)
        .validate()
        .set_task_instance_id("observers_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="off_transect_dist",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params.get("observers_distance") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_patrol_transects
        )
    )

    exclude_neg_off_transects = (
        task(filter_rows)
        .validate()
        .set_task_instance_id("exclude_neg_off_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="off_transect_dist",
            value=-1,
            reset_index=True,
            op="ne",
            **(params.get("exclude_neg_off_transects") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=observers_distance)
    )

    add_orig_geom = (
        task(add_orig_geometry)
        .validate()
        .set_task_instance_id("add_orig_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("add_orig_geom") or {}))
        .mapvalues(argnames=["gdf"], argvalues=exclude_neg_off_transects)
    )

    estimate_animal_position = (
        task(estimate_animal_positions)
        .validate()
        .set_task_instance_id("estimate_animal_position")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="dist_to_centre",
            angle_column="radialangle",
            preserve_original_as="orig_geometry",
            **(params.get("estimate_animal_position") or {}),
        )
        .mapvalues(argnames=["patrol_events"], argvalues=add_orig_geom)
    )

    zip_est_patrol_transects = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_est_patrol_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[estimate_animal_position, normalize_transect_underscores],
            **(params.get("zip_est_patrol_transects") or {}),
        )
        .call()
    )

    compute_ortho_dist = (
        task(add_off_transect_distance)
        .validate()
        .set_task_instance_id("compute_ortho_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            distance_column="ortho_dist",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params.get("compute_ortho_dist") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_est_patrol_transects
        )
    )

    exclude_neg_ortho_dist = (
        task(filter_rows)
        .validate()
        .set_task_instance_id("exclude_neg_ortho_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="ortho_dist",
            value=-1,
            reset_index=True,
            op="ne",
            **(params.get("exclude_neg_ortho_dist") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=compute_ortho_dist)
    )

    merge_transects = (
        task(merge_transect_lines)
        .validate()
        .set_task_instance_id("merge_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("merge_transects") or {}))
        .mapvalues(argnames=["transects"], argvalues=normalize_transect_underscores)
    )

    simplify_tolerance = (
        task(simplify_transects)
        .validate()
        .set_task_instance_id("simplify_tolerance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(tolerance=50, **(params.get("simplify_tolerance") or {}))
        .mapvalues(argnames=["transects"], argvalues=merge_transects)
    )

    buffer_transect_segments = (
        task(buffer_transects)
        .validate()
        .set_task_instance_id("buffer_transect_segments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            cap_style="flat",
            single_sided=False,
            resolution=5,
            distance=500,
            **(params.get("buffer_transect_segments") or {}),
        )
        .mapvalues(argnames=["transects"], argvalues=simplify_tolerance)
    )

    zip_events_buff_trans = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_events_buff_trans")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[exclude_neg_ortho_dist, buffer_transect_segments],
            **(params.get("zip_events_buff_trans") or {}),
        )
        .call()
    )

    filter_intersecting_events = (
        task(flag_events_intersecting_transect)
        .validate()
        .set_task_instance_id("filter_intersecting_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            intersects_column="intersects_transect",
            transect_id_column="transect_id",
            transect_name_column="name",
            index_column="id",
            **(params.get("filter_intersecting_events") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_events_buff_trans
        )
    )

    zip_filtered_events_trans = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filtered_events_trans")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[filter_intersecting_events, buffer_transect_segments],
            **(params.get("zip_filtered_events_trans") or {}),
        )
        .call()
    )

    visited_transects = (
        task(filter_visited_transects)
        .validate()
        .set_task_instance_id("visited_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            intersects_column="intersects_transect",
            transect_id_column="transect_id",
            transect_name_column="name",
            **(params.get("visited_transects") or {}),
        )
        .mapvalues(
            argnames=["patrol_events", "transects"], argvalues=zip_filtered_events_trans
        )
    )

    reproject_transects = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(target_crs="epsg:4326", **(params.get("reproject_transects") or {}))
        .mapvalues(argnames=["gdf"], argvalues=visited_transects)
    )

    survey_min_date = (
        task(get_survey_min_date)
        .validate()
        .set_task_instance_id("survey_min_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("survey_min_date") or {}))
        .mapvalues(argnames=["patrol_events"], argvalues=period_patrol_events)
    )

    zip_transects_min_date = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_transects_min_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[reproject_transects, survey_min_date],
            **(params.get("zip_transects_min_date") or {}),
        )
        .call()
    )

    add_since_transects = (
        task(add_constant_column)
        .validate()
        .set_task_instance_id("add_since_transects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="survey_date", **(params.get("add_since_transects") or {}))
        .mapvalues(argnames=["df", "value"], argvalues=zip_transects_min_date)
    )

    convert_trans_ee = (
        task(to_ee_feature_collection)
        .validate()
        .set_task_instance_id("convert_trans_ee")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=gee_client, **(params.get("convert_trans_ee") or {}))
        .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
    )

    zip_aoi_min_date = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_aoi_min_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[convert_trans_ee, survey_min_date],
            **(params.get("zip_aoi_min_date") or {}),
        )
        .call()
    )

    hls_ndvi_image = (
        task(build_hls_ndvi_image)
        .validate()
        .set_task_instance_id("hls_ndvi_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            ndvi_window_days=None,
            max_cloud_cover=30,
            ndvi_band_name="NDVI_HSL",
            **(params.get("hls_ndvi_image") or {}),
        )
        .mapvalues(argnames=["aoi", "since"], argvalues=zip_aoi_min_date)
    )

    create_slope_image = (
        task(build_slope_image)
        .validate()
        .set_task_instance_id("create_slope_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            dem_asset="USGS/SRTMGL1_003",
            **(params.get("create_slope_image") or {}),
        )
        .call()
    )

    woody_cover_image = (
        task(build_palsar_woody_cover_image)
        .validate()
        .set_task_instance_id("woody_cover_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            dry_season_start_month=7,
            dry_season_end_month=9,
            woody_cover_band_name="WoodyCover",
            **(params.get("woody_cover_image") or {}),
        )
        .mapvalues(argnames=["aoi", "since"], argvalues=zip_aoi_min_date)
    )

    label_ndvi_hsl = (
        task(label_features_with_image_stat)
        .validate()
        .set_task_instance_id("label_ndvi_hsl")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            image=create_slope_image,
            out_column="NDVI_HSL",
            region_reducer=None,
            scale=30.0,
            reducer_key="mean",
            **(params.get("label_ndvi_hsl") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=add_since_transects)
    )

    zip_ndvi_min_date = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_ndvi_min_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[label_ndvi_hsl, survey_min_date],
            **(params.get("zip_ndvi_min_date") or {}),
        )
        .call()
    )

    add_img_date_hsl_ndvi = (
        task(add_constant_column)
        .validate()
        .set_task_instance_id("add_img_date_hsl_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="img_date_hsl_ndvi", **(params.get("add_img_date_hsl_ndvi") or {})
        )
        .mapvalues(argnames=["df", "value"], argvalues=zip_ndvi_min_date)
    )

    label_slope = (
        task(label_features_with_image_stat)
        .validate()
        .set_task_instance_id("label_slope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            image=create_slope_image,
            out_column="slope",
            region_reducer=None,
            scale=30.0,
            reducer_key="mean",
            **(params.get("label_slope") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=add_img_date_hsl_ndvi)
    )

    zip_woody_cover_image = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_woody_cover_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[label_slope, woody_cover_image],
            **(params.get("zip_woody_cover_image") or {}),
        )
        .call()
    )

    label_woody_cover = (
        task(label_features_with_image_stat)
        .validate()
        .set_task_instance_id("label_woody_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            out_column="WoodyCover",
            region_reducer=None,
            scale=50.0,
            reducer_key="mean",
            **(params.get("label_woody_cover") or {}),
        )
        .mapvalues(argnames=["gdf", "image"], argvalues=zip_woody_cover_image)
    )

    filter_transect_columns = (
        task(select_columns)
        .validate()
        .set_task_instance_id("filter_transect_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "name",
                "img_date_hsl_ndvi",
                "NDVI_HSL",
                "slope",
                "WoodyCover",
                "geometry",
            ],
            raise_on_missing=True,
            **(params.get("filter_transect_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=label_woody_cover)
    )

    exclude_geom = (
        task(select_columns)
        .validate()
        .set_task_instance_id("exclude_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["name", "img_date_hsl_ndvi", "NDVI_HSL", "slope", "WoodyCover"],
            raise_on_missing=True,
            **(params.get("exclude_geom") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_transect_columns)
    )

    zip_patrol_transects_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_patrol_transects_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[filter_intersecting_events, exclude_geom],
            **(params.get("zip_patrol_transects_df") or {}),
        )
        .call()
    )

    merge_filtered_patrols = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_filtered_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_on="transect_id",
            right_on="name",
            how="left",
            left_index=False,
            right_index=False,
            fillna_value=None,
            on=None,
            **(params.get("merge_filtered_patrols") or {}),
        )
        .mapvalues(argnames=["left", "right"], argvalues=zip_patrol_transects_df)
    )

    select_patrol_event_cols = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_patrol_event_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "transect_id",
                "level_1",
                "title",
                "patrol_id",
                "patrol_serial_number",
                "totalcount",
                "num_juveniles",
                "event_type",
                "num_observers",
                "dist_to_centre",
                "geometry",
                "species",
                "other_species",
                "time",
                "serial_number",
                "radialangle",
                "survey_id",
                "off_transect_dist",
                "orig_geometry",
                "ortho_dist",
                "intersects_transect",
                "img_date_hsl_ndvi",
                "NDVI_HSL",
                "slope",
            ],
            raise_on_missing=False,
            **(params.get("select_patrol_event_cols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=merge_filtered_patrols)
    )

    combine_patrol_event_names = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_patrol_event_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            second="analysis_data", **(params.get("combine_patrol_event_names") or {})
        )
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_patrol_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_patrol_event_names, select_patrol_event_cols],
            **(params.get("zip_filename_patrol_df") or {}),
        )
        .call()
    )

    persist_patrol_events_csv = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_patrol_events_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            **(params.get("persist_patrol_events_csv") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=zip_filename_patrol_df)
    )

    select_gpkg_columns = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_gpkg_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "serial_number",
                "transect_id",
                "dist_to_centre",
                "ortho_dist",
                "intersects_transect",
                "geometry",
            ],
            raise_on_missing=False,
            **(params.get("select_gpkg_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=select_patrol_event_cols)
    )

    combine_gpkg_name = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_gpkg_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(second="events", **(params.get("combine_gpkg_name") or {}))
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_gpkg_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_gpkg_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_gpkg_name, select_gpkg_columns],
            **(params.get("zip_filename_gpkg_df") or {}),
        )
        .call()
    )

    persist_patrol_events_gpkg = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_patrol_events_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="gpkg",
            **(params.get("persist_patrol_events_gpkg") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=zip_filename_gpkg_df)
    )

    format_transect_names = (
        task(format_text_column)
        .validate()
        .set_task_instance_id("format_transect_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="name", method="lower", **(params.get("format_transect_names") or {})
        )
        .mapvalues(argnames=["df"], argvalues=filter_transect_columns)
    )

    combine_transect_gpkg_name = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_transect_gpkg_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            second="transect_areas", **(params.get("combine_transect_gpkg_name") or {})
        )
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_transect_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_transect_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_transect_gpkg_name, format_transect_names],
            **(params.get("zip_filename_transect_df") or {}),
        )
        .call()
    )

    persist_transects_gpkg = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_transects_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="gpkg",
            **(params.get("persist_transects_gpkg") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=zip_filename_transect_df)
    )

    zip_lines_visited = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_lines_visited")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[simplify_tolerance, visited_transects],
            **(params.get("zip_lines_visited") or {}),
        )
        .call()
    )

    visited_transect_lines = (
        task(filter_transect_lines_by_visited)
        .validate()
        .set_task_instance_id("visited_transect_lines")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(name_column="name", **(params.get("visited_transect_lines") or {}))
        .mapvalues(argnames=["lines", "visited"], argvalues=zip_lines_visited)
    )

    reproject_transect_lines = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_transect_lines")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            target_crs="epsg:4326", **(params.get("reproject_transect_lines") or {})
        )
        .mapvalues(argnames=["gdf"], argvalues=visited_transect_lines)
    )

    combine_transect_lines_gpkg_name = (
        task(join_with_underscore)
        .validate()
        .set_task_instance_id("combine_transect_lines_gpkg_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            second="transect_lines",
            **(params.get("combine_transect_lines_gpkg_name") or {}),
        )
        .mapvalues(argnames=["first"], argvalues=combine_survey_period_name)
    )

    zip_filename_transect_lines_df = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_filename_transect_lines_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_transect_lines_gpkg_name, reproject_transect_lines],
            **(params.get("zip_filename_transect_lines_df") or {}),
        )
        .call()
    )

    persist_transect_lines_gpkg = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_transect_lines_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="gpkg",
            **(params.get("persist_transect_lines_gpkg") or {}),
        )
        .mapvalues(
            argnames=["filename", "df"], argvalues=zip_filename_transect_lines_df
        )
    )

    zip_publish_paths = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_publish_paths")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[persist_transects_gpkg, persist_patrol_events_gpkg],
            **(params.get("zip_publish_paths") or {}),
        )
        .call()
    )

    gather_transects_paths = (
        task(collect_transects_paths)
        .validate()
        .set_task_instance_id("gather_transects_paths")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            zipped=zip_publish_paths, **(params.get("gather_transects_paths") or {})
        )
        .call()
    )

    gather_patrol_events_paths = (
        task(collect_patrol_events_paths)
        .validate()
        .set_task_instance_id("gather_patrol_events_paths")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            zipped=zip_publish_paths, **(params.get("gather_patrol_events_paths") or {})
        )
        .call()
    )

    publish_paths_text = (
        task(format_publish_paths)
        .validate()
        .set_task_instance_id("publish_paths_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            transects_paths=gather_transects_paths,
            patrol_events_paths=gather_patrol_events_paths,
            **(params.get("publish_paths_text") or {}),
        )
        .call()
    )

    publish_paths_widget = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("publish_paths_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Files ready to publish",
            data=publish_paths_text,
            **(params.get("publish_paths_widget") or {}),
        )
        .call()
    )

    overall_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("overall_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params.get("overall_dashboard") or {}),
        )
        .call()
    )

    return overall_dashboard
